version: 2.1

executors:
    node-standalone:
        docker:
            - image: circleci/node:14.16.0

jobs:
    deps-install:
        executor: node-standalone
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - yarn-cache-node14-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                      - yarn-cache-node14-{{ checksum "package.json" }}
                      - yarn-cache-node14
            - run:
                  name: Install depdencies
                  command: yarn install --frozen-lockfile --cache-folder ~/.cache/yarn
            - save_cache:
                  key: yarn-cache-node14-{{ checksum "package.json" }}-{{ checksum "yarn.lock" }}
                  paths:
                      - ~/.cache/yarn
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - node_modules

    validate-project:
        executor: node-standalone
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run:
                  name: Lint source code
                  command: yarn lint --format junit -o ./junit/js-lint-results.xml
            - run:
                  name: Build
                  command: yarn build
                  environment:
                      NODE_ENV: production
            - persist_to_workspace:
                  root: ~/project
                  paths:
                      - build
            - store_artifacts:
                  path: ~/project/build
                  destination: build
            - run:
                  name: Lint commit messages
                  command: node ./lint-commits.js
            - store_test_results:
                  path: ~/project/junit/

    release:
        executor: node-standalone
        steps:
            - checkout
            - attach_workspace:
                  at: ~/project
            - run:
                  name: semantic-release
                  command: yarn semantic-release

workflows:
    version: 2

    main:
        jobs:
            - deps-install
            - validate-project:
                  requires:
                      - deps-install
            - release:
                  context:
                      - html2pdf-release
                  filters:
                      branches:
                          only:
                              - master
                  requires:
                      - validate-project
