name: Docker

on:
  push:
    branches:
      - master
    tags:
      - v*

env:
  DOCKER_LOGIN: appvantageasia
  IMAGE_NAME: html2pdf-service

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.3.0'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Linting
        run: yarn lint

      - name: Build
        run: yarn build

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    permissions:
      contents: read
      packages: write

    steps:
      - name: Build image for chrome
        uses: ./.github/actions/docker-build
        with:
          dockerFile: docker/chrome/Dockerfile
          imageName: $IMAGE_NAME

      - name: Build image for chromium
        uses: ./.github/actions/docker-build
        with:
          dockerFile: docker/chromium/Dockerfile
          imageName: $IMAGE_NAME-chromium
